### PR TITLE
Allow for regular strings instead of only static strings

### PR DESCRIPTION
**Pull request by DaanDD**
Hello, thanks for creating this package!

I have made a small change, allowing for any tag string to be sent, not only static strings. Otherwise it was impossible to integrate in my code.

### CODE REVIEW

**Comment by johnmanjiro13** [comment]
Hi, @DaanDD
Thank you for your contribution!

I'd like to review this pr but I have no time because I'm on vacation now.
So, please wait a few days 🙏

**Comment by johnmanjiro13** [comment]
Could you merge main branch to yours because I fixed a test workflow?
After that, I will run tests and merge this pr.

**Comment by DaanDD** [comment]
@johnmanjiro13 Done!

**Review by johnmanjiro13 — APPROVED** [review]
LGTM

**Pull request merged**
